default:
  image: maven:3-openjdk-11
    
variables:
  REPO_DIR: "/${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/repo"
  TEST_OPTS: "-B -X -fae -DskipTests=false -DskipITs=false -Dmaven.test.failure.ignore=true"
  MAVEN_CLI_OPTS: "-B -X -fn -Dmaven.repo.local=${REPO_DIR} -DskipTests -DskipITs"

cache:
  key: mvncache
  paths:
    - ${REPO_DIR}

.show_env: &show_env
  - echo "home  ${HOME}"
  - printenv | sort

.show_repo: &show_repo
  - ls -la ${REPO_DIR}
  - du --max-depth=1 -h ${REPO_DIR}

build:
  before_script:
    - *show_env
    - mkdir -p ${REPO_DIR}
    - *show_repo
  script:
    - mvn ${MAVEN_CLI_OPTS} validate
    - echo mvn ${MAVEN_CLI_OPTS} verify
    - echo mvn ${MAVEN_CLI_OPTS} install
  after_script:
    - *show_repo
