install_jar:
  stage: .post
  variables:
    GLOBAL_POM_V: 0.2.1
    GLOBAL_POM_URL: https://gitlab.com/ollily/global-pom.git
    GLOBAL_POM_DIR: $CI_PROJECT_DIR/.deps/global-pom/0.2.1
    GLOBAL_POM_FILE: $CI_PROJECT_DIR/.deps/global-pom/0.2.1/pom.xml
    GLOBAL_POM_INSTALL: "-DgroupId=com.glowa-net.maven.parent -DartifactId=global-pom -Dversion=$GLOBAL_POM_V -Dpackaging=pom"
  before_script:
    - mkdir -p -v $GLOBAL_POM_DIR
    - git clone -v -b $GLOBAL_POM_V $GLOBAL_POM_URL $GLOBAL_POM_DIR
  script:
    - mvn $MVN_CLI_OPTS install:install-file -f $GLOBAL_POM_DIR -Dfile=$GLOBAL_POM_DIR $GLOBAL_POM_INSTALL
  