default:
  image: maven:3-openjdk-11

stages:
  - .pre
  - build
  - test
  - analyze
  - install
  - .post
      
variables:
  REPO_DIR: $CI_PROJECT_DIR/.repo
  MVN_TEST_OPTS: -B -fae -Dmaven.repo.local=$CI_PROJECT_DIR/.repo -DskipTests=false -DskipITs=false -Dmaven.test.failure.ignore=true
  MVN_CLI_OPTS: -B -fn -Dmaven.repo.local=$CI_PROJECT_DIR/.repo -DskipTests -DskipITs

cache:
  key: $CI_PROJECT_PATH_SLUG
  when: always
  paths:
    - $REPO_DIR

.show_env: &show_env
  - echo "show_env"
  - printenv | sort

.show_build: &show_build
  - echo "show_build"
  - find $CI_BUILDS_DIR -type d -print

.show_repo: &show_repo
  - echo "show_repo"
  - du --max-depth=2 -h $REPO_DIR

build_jar:
  stage: build
  before_script:
    - *show_env
    - echo "creating $REPO_DIR"
    - mkdir -p $REPO_DIR
    - *show_repo
  script:
    - mvn $MVN_TEST_OPTS verify
    - *show_build
    - *show_repo

install_jar:
  include: 
    - local: '/.gitlab-install.yml'
     