default:
  image: maven:3-openjdk-11
    
variables:
  REPO_DIR: "$CI_PROJECT_DIR/.repo"
  MVN_TEST_OPTS: "-B -X -fae -Dmaven.repo.local=$REPO_DIR -DskipTests=false -DskipITs=false -Dmaven.test.failure.ignore=true"
  MVN_CLI_OPTS: "-B -X -fn -Dmaven.repo.local=$REPO_DIR -DskipTests -DskipITs"

cache:
  key: $CI_PROJECT_PATH_SLUG
  when: always
  paths:
    - $REPO_DIR

.show_env: &show_env
  - echo "show_env"
  - echo "home  $HOME"
  - echo "pwd $PWD"
  - echo "#$MVN_TEST_OPTS#"
  - echo "#$MVN_CLI_OPTS#"
  - printenv | sort

.show_build: &show_build
  - echo "show_build"
  - find $CI_BUILDS_DIR -type d -print

.show_repo: &show_repo
  - echo "show_repo"
  - ls -la $REPO_DIR
  - du --max-depth=1 -h $REPO_DIR

build:
  stage: build
  before_script:
    - *show_env
    - echo "creating $REPO_DIR"
    - mkdir -p $REPO_DIR
    - *show_repo
  script:
    - mvn $MVN_TEST_OPTS verify
    - mvn $MVN_CLI_OPTS install
  after_script:
    - *show_repo
    - *show_build
