image: maven:latest

stages:
  - validate
  - build
  - install

variables:
#  MAVEN_SETTIGNS: "-s ${HOME}/.m2/settings.xml"
  MAVEN_CLI_OPTS: "-B -X -DskipTests -DskipITs"
#  MAVEN_OPTS: "-Dmaven.repo.local=${HOME}/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

validate:
  stage: validate
  script:
    - mvn $MAVEN_CLI_OPTS validate

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS build

install:
  stage: install
  script:
    - mvn $MAVEN_CLI_OPTS install
  only:
    - master
