#
# Config
os: linux
sudo: false
cache:
  directories:
    - "$HOME/.m2"

language: java
jdk: openjdk11

#
# Steps
before_install:

install:
#   - mvn -B -V -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true

before_script:

script:
  - mvn -B -V -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true clean verify

after_script:
  - mvn -B -DskipTests=true -DskipITs=true -Dmaven.test.failure.ignore=true -DSONAR_TOKEN=${SONAR_TOKEN_global-pom} org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

#
# Finally

after_success:

after_failure:
