#
# Config
os: linux
sudo: false
env:
  - SONAR_TOKEN=${travis2sonar}
cache:
  directories:
    - "$HOME/.m2"

language: java
jdk: openjdk11

#
# Steps
before_install: skip

install: skip
#   - mvn -B -V -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true

before_script: skip

script:
  - mvn -B -V -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true clean install

after_script:
  - mvn -B -DskipTests=true -DskipITs=true -Dmaven.test.failure.ignore=true org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

#
# Finally

after_success: skip

after_failure: skip
