name: sonarcloud-analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      # - '.github/**'
      - '.run/**'
      - '.m2/**'
      - '.repo/**'

env:
  # Github Additional Configuration
  GITHUB_REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_PROJECT_DIR: ${{ github.workspace }}

  GITHUB_TARGET_DIR: ${{ github.workspace }}/target
  GITHUB_UPLOAD_DIR: ${{ github.workspace }}/target/staging
  GITHUB_UPLOAD_NAME: ${{ github.event.repository.name }}.zip
  GITHUB_BRANCH_NAME: ${{ github.ref_name }}



  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PCK_READ_TOKEN: ${{ secrets.PCK_READ_TOKEN }}
  PCK_WRITE_TOKEN: ${{ secrets.PCK_WRITE_TOKEN }}

  # Maven Common Configuration
  MVN_HOME_DIR: ~/.m2
  MVN_REPO_JOB_DIR: ~/.m2/repository
  MVN_SETT_OPTS: -V -B
  MVN_SETS_OPTS: -V -B -s "${{ github.workspace }}/.m2/settings.xml"
  MVN_REPO_OPTS: -Dmaven.repo.local=" ~/.m2/repository"

  # Maven Sign Configuration
  MVN_SIGN_OPTS: -P!generate-gpgkey -P!sign-jar

  # Maven Test Configuration
  MVN_TEST_OPTS_N: -DskipTests=true -DskipITs=true -Dmaven.test.failure.ignore=true
  MVN_TEST_OPTS_Y: -DskipTests=false -DskipITs=false -Dmaven.test.failure.ignore=true

  # Maven Goal Options
  MVN_CLI_OPTS: -ff
  MVN_BUILD_OPTS: -fae -Dmaven.test.failure.ignore=true
  MVN_DEPLOY_OPTS: -Pdeploy-jfrog -DfastBuild -DretryFailedDeploymentCount=10

  # Sonarcloud Configuration
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_CACHE_DIR: ~/.sonar/cache
  SONAR_HOST_URL: "https://sonarcloud.io"
  MVN_SONAR_OPTS: -Dsonar.qualitygate.wait=false -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # Codacy Configuration
  MVN_CODACY_OPTS: -DcoverageReportFile=target/jacoco/comm/jacoco.xml -DprojectToken=${{ secrets.CODACY_PROJECT_TOKEN }} -DapiToken=${{ secrets.CODACY_API_TOKEN }}

  # Coveralls Configuration
  MVN_COVERALLS_OPTS: -Dbranch=${{ github.ref_name }} -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}

  # JFrog Configuration
  JF_WRITE_TOKEN: ${{ secrets.JF_WRITE_TOKEN }}

jobs:
  sonarcloud:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [11]
        distribution: [adopt]
    runs-on: ${{ matrix.os }}

    steps:
      - name: show env
        run: |
          printenv | sort

      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: setup JDK
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '${{ matrix.version }}'
          distribution: '${{ matrix.distribution }}'
          architecture: x64

      - name: cache maven packages
        uses: actions/cache@v3.3.1
        with:
          path: ${{ env.MVN_HOME_DIR }}
          key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-m2

      - name: cache sonarcloud packages
        uses: actions/cache@v3.3.1
        with:
          path: ${{ env.SONAR_CACHE_DIR }}
          key: ${{ matrix.os }}-sonar
          restore-keys: ${{ matrix.os }}-sonar

      - name: show_m2
        run: |
          test -f ${{ env.MVN_HOME_DIR }}/settings.xml && cat ${{ env.MVN_HOME_DIR }}/settings.xml

      - name: show settings
        run: cat ${{ github.workspace}}/.m2/settings.xml

      - name: show_repo
        run: |
          du --max-depth=1 -h ${{ env.MVN_REPO_JOB_DIR }}

      #      - name: codacy coverage upload
      #        run: mvn ${{ env.MVN_SETS_OPTS }} ${{ env.MVN_SIGN_OPTS }} ${{ env.MVN_TEST_OPTS_Y }} ${{ env.MVN_CODACY_OPTS }} help:active-profiles verify com.gavinmogan:codacy-maven-plugin:coverage

      #      - name: coveralls scan
      #        run: mvn ${{ env.MVN_SETS_OPTS }} ${{ env.MVN_SIGN_OPTS }} ${{ env.MVN_TEST_OPTS_Y }} ${{ env.MVN_COVERALLS_OPTS }} help:active-profiles verify coveralls:report

      - name: sonarcloud scan
        run: mvn ${{ env.MVN_SETS_OPTS }} ${{ env.MVN_SIGN_OPTS }} ${{ env.MVN_TEST_OPTS_Y }} ${{ env.MVN_SONAR_OPTS }} help:active-profiles verify sonar:sonar
